name: Auto run hosts

on:
  schedule:
    - cron: '0 8 * * *'  # 每天早上8点（UTC时间）触发
  push:  # 也可以在代码被推送到仓库时触发

jobs:
  hosts:  # 定义一个名为build的job
    runs-on: ubuntu-latest  # 指定运行环境为最新的Ubuntu

    steps:
    - uses: actions/checkout@v3  # 检出代码到运行环境
    - name: Set up Python  # 设置Python环境
      uses: actions/setup-python@v4  # 使用setup-python Action
      with:
        python-version: '3.10'  # 指定Python版本
    - name: Run Python script  # 运行Python脚本
      run: |
        python ./domain_to_ip.py  # 执行main.py脚本
