name: Auto run hosts

on:
  schedule:
    - cron: '0 8 * * *'  # 每天早上8点（UTC时间）触发
  push:  # 也可以在代码被推送到仓库时触发

jobs:
  hosts:  # 定义一个名为hosts的job
    runs-on: ubuntu-latest  # 指定运行环境为最新的Ubuntu

    steps: # 步骤
    - uses: actions/checkout@v3  # 检出代码到运行环境
    
    - name: Set up Python  # 设置Python环境
      uses: actions/setup-python@v4  # 使用setup-python Action
      with:
        python-version: '3.10'  # 指定Python版本

    - name: Install dependencies #安装环境
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Run Python script  # 运行Python脚本
      run: |
        python ./domain_to_ip.py  # 执行domain_to_ip.py脚本
        
    - name: Commit #提交代码
      id: commit
      run: |
          git config --global user.email aieng07c@gmail.com
          git config --global user.name AiENG07
          git add .
          git commit -m "Update hosts"
      continue-on-error: true
      
    - name: Check on failures
      if: steps.commit.outputs.status == 'failure'
      run: exit 1

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.COMMIT_TOKEN }}

    
